#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())
    result = 0
    for j in range(1, 11):
        result = n * j
        print(n, "x", j, "=" ,result)
