#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    N = int(input())
    d = []
    
    for N_itr in range(N):
        firstNameEmailID = input().split()

        firstName = firstNameEmailID[0]
        
        emailID = firstNameEmailID[1]
        
        if '@gmail.com' in emailID:
            d.append(firstName)
    d.sort()
    for i in d:
        print(i)
